Vocabulary:
    type: entity
    table: taxonomy_vocabulary
    repositoryClass: ActiveLAMP\Taxonomy\Entity\Repository\VocabularyRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        labelName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: label_name
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    oneToMany:
        terms:
            targetEntity: TermInterface
            cascade:
                - remove
            mappedBy: vocabulary
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
